FROM openjdk:17-jdk-slim

RUN apt-get update && apt-get install -y curl maven git && apt-get clean

WORKDIR /app

ARG CACHE_VER=24
RUN git clone -b ianressa/license https://github.com/ianressa/goblinweaver.git /app
RUN git pull origin ianressa/license

RUN mvn clean package

RUN chmod -R 777 /app/target

# Entry point
CMD exec java -Dneo4jUri=bolt://neo4jMaven:7687 -Dneo4jUser=neo4j -Dneo4jPassword=Password1 -jar /app/target/goblinWeaver-2.1.0.jar noUpdate

EXPOSE 8080